# .github/workflows/test-action.yml
name: Test Custom Action

on:
  push:
  workflow_dispatch:

jobs:
  run-custom-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run custom action
        uses: ${{ github.actor }}AME/YOUR_CUSTOM_ACTION_REPO_NAME@main
